[package]
name = "effect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yahoo_finance_api = { version = "2" }
tokio = { version = "1", features = ["full"] }
time = { version = "0.3", features = ["serde-human-readable"] }
serde = "1"
serde_yaml = "0.9"
anyhow = "1"
axum = "0.7"
polars = { version = "0.36", features = [
    "temporal",
    "lazy",
    "csv",
    "parquet",
    "serde",
    "polars-io",
    "polars-ops",
    "cum_agg",
    "strings",
    "dtype-decimal",
    "polars-plan",
] }
polars-plan = { version = "0.36", features = ["regex"] }
clap = { version = "4", features = ["derive"] }
