// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BankFormat } from "./BankFormat";
import type { ExtendedLedgerRecord } from "./ExtendedLedgerRecord";

export type Account = { id: string, name: string, currency: string, format: BankFormat, records: Array<ExtendedLedgerRecord>, initial_balance: number | null, initial_date: number, spending: boolean, };