// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Format } from "./Format";

export type CreateLedgerRequest = { transactions_data: string, format: Format, initial_balance: number | null, initial_date: number, name: string, currency: string, spending: boolean, };