// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExtendedLedgerRecord = { date: number, amount: number, description: string, original_description: string, category: string, original_category: string, comments: string, checked: boolean, symbol: string, };