// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtendedLedgerRecord } from "./ExtendedLedgerRecord";
import type { LedgerKind } from "./LedgerKind";
import type { Symbol } from "./Symbol";

export type ExtendedLedger = { name: string, symbol: Symbol, records: Array<ExtendedLedgerRecord>, kind: LedgerKind, };