// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LedgerFile = { filename: string, number_of_entries: number | null, error: string | null, };