// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LedgerFile } from "./LedgerFile";

export type LedgerFiles = { id: string, files: Array<LedgerFile>, };