// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SpendingSummary } from "./SpendingSummary";

export type LedgerSummary = { spending: { [key: string]: SpendingSummary }, };