// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortfolioLedgersData } from "./PortfolioLedgersData";

export type PortfolioSummaryResponse = { total_balance: PortfolioLedgersData, };