// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Currency } from "./Currency";

export type PortfolioLedgerData = { id: string, name: string, currency: Currency, series: Array<number>, };