// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortfolioLedgerData } from "./PortfolioLedgerData";

export type PortfolioLedgersData = { balances: Array<PortfolioLedgerData>, timestamps: number[], };