// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PortfolioLedgerData } from "./PortfolioLedgerData";
import type { PortfolioLedgersData } from "./PortfolioLedgersData";
import type { SpendPerMonth } from "./SpendPerMonth";

export type PortfolioSummaryResponse = { total_balance: PortfolioLedgersData, total_prediction: PortfolioLedgerData, spend_per_month: SpendPerMonth, };