// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpendPerMonth = {
  months: { [key: number]: { [key: number]: { [key: string]: number } } };
};
