// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BankFormat } from "./BankFormat";

export type UpdateLedgerRequest = { format: BankFormat, initialBalance: number | null, initialDate: number, name: string, spending: boolean, };